In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr)
print(type(arr))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a+10)



[11 12 13 14]


In [2]:
import numpy as np
a = np.array([1,2,3])
b = np.array([3,4,5])
print(np.dot(a,b))

26


In [3]:
import numpy as np
a=np.array([[1,2],
            [3,4],[5,6]])
print(a.T)

[[1 3 5]
 [2 4 6]]


In [4]:
import numpy as np
a=np.array([[1,2,3],
            [3,4,6],
            [3,4,5]])
print(np.linalg.norm(a))

11.180339887498949
