In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr)
print(type(arr))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a+10)



[11 12 13 14]


In [2]:
import numpy as np
a = np.array([1,2,3])
b = np.array([3,4,5])
print(np.dot(a,b))

26


In [3]:
import numpy as np
a=np.array([[1,2],
            [3,4],[5,6]])
print(a.T)

[[1 3 5]
 [2 4 6]]


In [4]:
import numpy as np
a=np.array([[1,2,3],
            [3,4,6],
            [3,4,5]])
print(np.linalg.norm(a))

11.180339887498949


In [1]:
import numpy as np
a=np.array([[1,2,5],
            [3,4,6],
            [3,4,5]])
print(np.linalg.inv(a))            

[[-2.   5.  -4. ]
 [ 1.5 -5.   4.5]
 [-0.   1.  -1. ]]


In [1]:
import numpy as np
data = np.array([10, 20, 30, 40, 50])
print("Data:", data)
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))
print("Minimum value:", np.min(data))
print("Maximum value:", np.max(data))
print("Sum:", np.sum(data))

Data: [10 20 30 40 50]
Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Variance: 200.0
Minimum value: 10
Maximum value: 50
Sum: 150


In [2]:
import numpy as np
data = np.array([[10, 20, 30],
                 [40, 50, 60]])
print("Array:\n", data)
print("Mean (row-wise):", np.mean(data, axis=1))
print("Mean (column-wise):", np.mean(data, axis=0))

Array:
 [[10 20 30]
 [40 50 60]]
Mean (row-wise): [20. 50.]
Mean (column-wise): [25. 35. 45.]
